### ISSUE TITLE
Something's wrong with Xcache config

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#1410]
Trying to run a cake shell command, for instance:
```
$ Console/cake sphinx_conf > sphinx.conf
```

Will output this error:
```
PHP Fatal error:  Uncaught exception 'CacheException' with message 'Cache engine "default" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct' in /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php:186
Stack trace:
#0 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('default')
#1 /var/www-dev/app/Config/core.php(365): Cache::config('default', Array)
#2 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Core/Configure.php(72): include('/var/www-dev/ap...')
#3 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#4 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(145): require('/var/www-dev/ap...')
#5 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(100): ShellDispatcher->_bootstrap()
#6 /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Console/ShellDispatcher.php(54): ShellDispatcher->_initEnvironment()
#7 /var/www-dev/ap in /var/www-dev/app/Vendor/cakephp/cakephp/lib/Cake/Cache/Cache.php on line 186
````

Note: as a temporary fix for the prod website, I've commented out the Xcache config and used the File cache instead:
```
Cache::config('default', array('engine' => 'File'));
```

**Comment by trang** [comment]
So we've had this config for over a year now. I guess I'm closing this. We can open another issue when we want to set up Xcache again (or any other cache).
