### ISSUE TITLE
Members can't upload profile images (avatars).

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1509]
A fairly new member has sent me a message saying that he/she has tried uploading one several times, but keeps getting an error message.

**Comment by ckjpn** [comment]
Here's a PM from that member from 12 hours ago.


About this: here's the error message displayed on https://tatoeba.org/eng/user/save_image :

An Internal Error Has Occurred.

Error: An Internal Error Has Occurred.

**Comment by trang** [comment]
I think this is due to `imagick` not being installed. @Ppjet6 if it's easy to do, could you install it?

**Comment by trang** [comment]
Seems like this is not easy to solve.

I switched level debug to 1 temporarily and tried to upload a new profile picture. Got this error:

```
Error: Uncaught FatalErrorException: [CakeException] Unknown status code #0 /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(450) #1 /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(ImagickException)) #2 /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render() #3 [internal function]: ErrorHandler::handleException(Object(ImagickException)) #4 {main} in /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php:138 Stack trace: #0 /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(256, '[CakeException]...', '/var/www-prod-6...', 138) #1 [internal function]: ErrorHandle
File: /var/www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048/app/Vendor/cakephp/cakephp/lib/Cake/Error/ErrorHandler.php
Line: 138

Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp
```

I have to say this doesn't speak much to me...

**Comment by trang** [comment]
It was a permission issue.
