### ISSUE TITLE
Horus stopped working

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1563]
It seems that Horus stopped working, and its last activity is from 17-18 days ago. I noticed it since this duplicate https://tatoeba.org/ita/sentences/show/6930980 (which is the duplicate of https://tatoeba.org/ita/sentences/show/119812) went through, and I think that there are also other duplicates that went through.

**Comment by trang** [comment]
Problem was that the script that runs Horus was pointing to the wrong directory.

The installation of Horus was done in `www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff` so as a temporary solution I edited the `dedup.sh` script to point to that folder. It was pointing to `www-prod` which is a symlink. Every time we deploy changes we now create a new folder, and the new folders don't have Horus installed.

We will need to do a full scan at some point to fix the duplicates that were created in the last 18 days.

And we should extract Horus out of Tatoeba's code, I think.

**Comment by trang** [comment]
Seeing that Horus didn't duplicate anything yet, I tried to make him check sentences in the past 3 hours. Got some error...

```
Running incremental scan at 2018-06-07 11:46 PM UTC
Running filter on sentences added since 2018-06-07 08:46 PM
OK filtered 173 sentences
Running filter on sentences to find duplicates
OK 1 duplicate sets found
Running deduplication transactions on duplicate sets
Traceback (most recent call last):
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/dedup/management/commands/deduplicate.py", line 597, in handle
    self.suppress_error(self.deduplicate, main_sent, ids, post_cmnt, dry)
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/dedup/management/commands/deduplicate.py", line 371, in suppress_error
    cls.file_log.info(json.dumps(entry))
  File "/usr/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Sentences: Sentences object> is not JSON serializable
```

**Comment by trang** [comment]
Getting another error when trying a full scan...
```
$ python manage.py deduplicate -l /var/log/ -a dedup.log -bHorus -c
Running full scan at 2018-06-10 04:52 PM UTC
Running full table scan in 10 queries
Running duplicate filtering on sentence range: [1L, 693823L]
OK
Running duplicate filtering on sentence range: [693824L, 1387646L]
OK
Running duplicate filtering on sentence range: [1387647L, 2081469L]
OK
Running duplicate filtering on sentence range: [2081470L, 2775292L]
OK
Running duplicate filtering on sentence range: [2775293L, 3469115L]
OK
Running duplicate filtering on sentence range: [3469116L, 4162938L]
OK
Running duplicate filtering on sentence range: [4162939L, 4856761L]
OK
Running duplicate filtering on sentence range: [4856762L, 5550584L]
OK
Running duplicate filtering on sentence range: [5550585L, 6244407L]
OK
Running duplicate filtering on sentence range: [6244408L, 6938230L]
OK
OK full table scan and filtering done 6565762 duplicate sets found
Running deduplication step
Deduplication: 0% doneTraceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/dedup/management/commands/deduplicate.py", line 644, in handle
    self.deduplicate(main_sent, ids, post_cmnt, dry)
  File "/usr/local/lib/python2.7/dist-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/dedup/management/commands/deduplicate.py", line 388, in deduplicate
    cls.update_merge('TagsSentences', main_sent.id, ids)
  File "/var/www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff/docs/tatoeba2-django/dedup/management/commands/deduplicate.py", line 285, in update_merge
    get_model('tatoeba2.'+model).objects.filter(**{update_fld+'__in': ids}).update(**{update_fld: main_id})
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 583, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1004, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 128, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 207, in execute
    if not self._defer_warnings: self._warning_check()
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 117, in _warning_check
    warn(w[-1], self.Warning, 3)
_mysql_exceptions.Warning: Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statement is unsafe because it invokes a trigger or a stored function that inserts into an AUTO_INCREMENT column. Inserted values cannot be logged correctly.
```

**Comment by trang** [comment]
I think the installation Horus was not configured properly in `www-prod-b5017561ea65ebb7f4ca02cbe621d52324c6efff`.

I found out Horus was installed in `www-prod-6ccf087c9fe73886d7c1a4f1ddd7f69804d10048` as well. From there it works.
