### ISSUE TITLE
Internal error when opening the latest contributions' page

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#1879]
Every time I try to open the page containing the latest contributions (https://tatoeba.org/ita/contributions/latest), I get an internal error (no other useful debug info to add to the report is printed, apart from that, sadly). Every other page I tried works properly.

**Comment by jiru** [comment]
This bug is not visible any more because it came from a log entry that is not visible on the latest contributions page any more. For some reason, sentence 7883270 creation log entry has a zero date, and it failed the obsoletizer code in this way:

```
2019-05-02 07:43:40 Error: [Error] Call to a member function toUnixString() on null
#0 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/src/View/Helper/LogsHelper.php(68): App\View\Helper\LogsHelper->_findLatestContributionDates(Object(Cake\ORM\ResultSet))
#1 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/src/Template/Contributions/latest.ctp(76): App\View\Helper\LogsHelper->obsoletize(Object(Cake\ORM\ResultSet))
#2 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/View/View.php(1413): include('/var/www-prod-b...')
#3 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/View/View.php(1374): Cake\View\View->_evaluate('/var/www-prod-b...', Array)
#4 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/View/View.php(880): Cake\View\View->_render('/var/www-prod-b...')
#5 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Controller/Controller.php(791): Cake\View\View->render(NULL, NULL)
#6 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(126): Cake\Controller\Controller->render()
#7 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\ContributionsController))
#8 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(65): AssetCompress\Middleware\AssetCompressMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /var/www-prod-bdaec405198bd9fd17f7206656d68888231e5e4d/webroot/index.php(40): Cake\Http\Server->run()
#21 {main}
Request URL: /eng/contributions/latest
Referer URL: https://tatoeba.org/eng/
```

**Comment by jiru** [comment]
I found the cause of the zero date and opened a new issue for that: #1881.

**Comment by Guybrush88** [comment]
cool, thanks
