### ISSUE TITLE
Homepage isn't working properly

### ISSUE THREAD

**Issue by Guybrush88** [Tatoeba/tatoeba2#2577]
**To Reproduce**
1. Go to the homepage
2. See wrong layout; plus the latest contribution section isn't shown

**Expected behavior**
The homepage should be shown properly

**Screenshots (if applicable)**
https://i.ibb.co/jVVzsRS/Istantanea-2020-10-31-07-28-33.png

**Additional information (if relevant)**
- O.S.; Xubuntu 20.10
- Firefox 82.0

**Comment by Guybrush88** [comment]
It has been reported also on the wall: https://tatoeba.org/ita/wall/show_message/36073#!#message_36073

**Comment by trang** [comment]
I'm looking into it. It's perhaps because of this error:

```
2020-10-31 15:05:25 Error: [Error] Call to a member function formatContent() on null
#0 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/src/View/Helper/WallHelper.php(153): App\View\Helper\WallHelper->preview('I opened a bug ...', 200, 100)
#1 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/src/Template/Pages/index.ctp(73): App\View\Helper\WallHelper->messagePreview(36075, 'Guybrush88', 'I opened a bug ...', Object(Cake\I18n\FrozenTime))
#2 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/View/View.php(1419): include('/var/www-prod-2...')
#3 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/View/View.php(1380): Cake\View\View->_evaluate('/var/www-prod-2...', Array)
#4 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/View/View.php(880): Cake\View\View->_render('/var/www-prod-2...')
#5 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Controller/Controller.php(796): Cake\View\View->render(NULL, NULL)
#6 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(126): Cake\Controller\Controller->render()
#7 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\PagesController))
#8 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#10 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#12 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#13 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#14 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#15 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(65): AssetCompress\Middleware\AssetCompressMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#16 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#17 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#18 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#20 /var/www-prod-2c4c52148ab4bd4e49a0053094b97c3ff4081672/webroot/index.php(40): Cake\Http\Server->run()
#21 {main}
Request URL: /eng/
Referer URL: https://tatoeba.org/eng/

```

**Comment by trang** [comment]
@Guybrush88 The homepage should be working again now. Let me know if it works for you.

**Comment by Guybrush88** [comment]
I can confirm it works, thanks for the very quick fix
