### ISSUE TITLE
Cannot disable some audio

### ISSUE THREAD

**Issue by trang** [Tatoeba/tatoeba2#2947]
**To Reproduce**

1. Be logged in as admin.
2. Go to https://tatoeba.org/en/sentences/show/3991877
3. In the audio section, unchanged "Is enabled".
4. Click "Save".
5. Nothing happens.

**Expected behavior**
The audio should be disabled when I click "Save".

**Additional information**
Error in the logs:
```
2022-05-30 14:56:21 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created' cannot be null
[...]
Request URL: /en/audio/save/240783
Referer URL: https://tatoeba.org/en/sentences/show/3991877
```

This bug was reported in https://github.com/Tatoeba/tatoeba2/issues/183#issuecomment-1140814044. It cannot be reproduced with all audio. According to CK, some audio could be disabled but the one mentioned in this issue could not be disabled.

**Comment by ckjpn** [comment]
This is another one I couldn't disable.

https://tatoeba.org/en/sentences/show/2238804

However I was able to delete it, before uploading it's replacement.

**Comment by ckjpn** [comment]
https://tatoeba.org/en/sentences/show/3991877 still can't be edited because the audio can't be disabled.

Other times, it seems I've been able to successfully disable the audio and then edit the sentences, and then re-enable the audio.

Since this is taking a long time to fix, would it be OK, if I downloaded the audio file, then deleted the audio file, then re-upload the audio file?  Or, would you like to keep this one, so you can figure out the bug?

**Comment by trang** [comment]
@ckjpn Yes, you can delete and re-upload the audio for https://tatoeba.org/en/sentences/show/3991877.

It looks like this bug happens because the `created` date is `0000-00-00 00:00:00`.

``` 
MariaDB [tatoeba]> select * from audios where id = 240783;
+--------+-------------+---------+----------+---------------------+---------------------+
| id     | sentence_id | user_id | external | created             | modified            |
+--------+-------------+---------+----------+---------------------+---------------------+
| 240783 |     3991877 |    1396 | null     | 0000-00-00 00:00:00 | 2022-06-12 18:00:26 |
+--------+-------------+---------+----------+---------------------+---------------------+
``` 

There are 334k+ audio like that.

```
MariaDB [tatoeba]> select count(*) from audios where created = '0000-00-00 00:00:00';
+----------+
| count(*) |
+----------+
|   334757 |
+----------+
```

**Comment by ckjpn** [comment]
I've downloaded it, then deleted it, made the correction, and then re-uploaded the file.
I'll plan to do the same in the future if and when I encounter the same problem.
https://tatoeba.org/en/sentences/show/3991877

**Comment by ckjpn** [comment]
I don't know if this will help, but here is another one that couldn't be disabled.
I've deleted that file and uploaded a new one.
https://tatoeba.org/en/sentences/show/17520

**Comment by trang** [comment]
I've ran into another type of error that prevents saving audio:

```
2022-09-21 11:01:30 Error: [Cake\Http\Exception\NotFoundException] Not Found (/var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/src/Controller/AudioController.php:222)
#0 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Controller/Controller.php(609): App\Controller\AudioController->save('30186')
#1 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#2 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\AudioController))
#3 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/BaseApplication.php(234): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#4 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#5 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#6 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/src/Middleware/LanguageSelectorMiddleware.php(75): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#7 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): App\Middleware\LanguageSelectorMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#8 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#9 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(170): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/markstory/asset_compress/src/Middleware/AssetCompressMiddleware.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): AssetCompress\Middleware\AssetCompressMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/vendor/cakephp/cakephp/src/Http/Server.php(97): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /var/www-prod-566345dc66fcff88f3018ce72c623bd3a9eefb87/webroot/index.php(40): Cake\Http\Server->run()
#20 {main}
Request URL: /en/audio/save/30186
Referer URL: https://tatoeba.org/en/sentences/show/377970

```
Not sure why this one is happening...

**Comment by jiru** [comment]
This issue is still happening.

Audios added before [2017-02-12](https://github.com/Tatoeba/tatoeba2/milestone/131?closed=1) have a `created` field set to zero. That was fine until the change introduced by 0c606a2c9905ae6ea76f8d4e1066d6810bc6d68e (and deployed on 2022-05-01): disabled audios are moved into a separate table, which means disabling an audio is equivalent to creating a new record in a separate table that share the same constraints. One of these constraints is that `created` cannot be null or `0000-00-00 00:00:00`.
